[package]
name = "metar_taf"
version = "0.1.0"
authors = ["Username23-23 <69996778+Username23-23@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
